-- CreateTable
CREATE TABLE "system_settings" (
    "id" TEXT NOT NULL,
    "companyName" TEXT,
    "companyLogo" TEXT,
    "companyAddress" TEXT,
    "companyPhone" TEXT,
    "companyEmail" TEXT,
    "companyWebsite" TEXT,
    "companyTaxId" TEXT,
    "currency" TEXT NOT NULL DEFAULT 'CHF',
    "dateFormat" TEXT NOT NULL DEFAULT 'DD.MM.YYYY',
    "timeFormat" TEXT NOT NULL DEFAULT 'HH:mm',
    "language" TEXT NOT NULL DEFAULT 'de',
    "timezone" TEXT NOT NULL DEFAULT 'Europe/Zurich',
    "autoBackupEnabled" BOOLEAN NOT NULL DEFAULT false,
    "backupInterval" TEXT NOT NULL DEFAULT 'daily',
    "backupTime" TEXT NOT NULL DEFAULT '02:00',
    "backupRetention" INTEGER NOT NULL DEFAULT 30,
    "lastBackupAt" TIMESTAMP(3),
    "smtpEnabled" BOOLEAN NOT NULL DEFAULT false,
    "smtpHost" TEXT,
    "smtpPort" INTEGER NOT NULL DEFAULT 587,
    "smtpSecure" BOOLEAN NOT NULL DEFAULT true,
    "smtpUser" TEXT,
    "smtpPassword" TEXT,
    "smtpFromEmail" TEXT,
    "smtpFromName" TEXT,
    "invoicePrefix" TEXT NOT NULL DEFAULT 'RE-',
    "invoiceNumberStart" INTEGER NOT NULL DEFAULT 1000,
    "invoiceNumberPadding" INTEGER NOT NULL DEFAULT 4,
    "invoiceTermsDays" INTEGER NOT NULL DEFAULT 30,
    "invoiceFooter" TEXT,
    "enableWorkflows" BOOLEAN NOT NULL DEFAULT true,
    "enableIncidents" BOOLEAN NOT NULL DEFAULT true,
    "enableCompliance" BOOLEAN NOT NULL DEFAULT true,
    "enableTimeTracking" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id")
);
